---
title: "Portfolios of 5 Assets"
author: "Bach Tran"
date: "2025-04-02"
output: html_document
---

```{r setup, warning = FALSE, message = FALSE}
library(dplyr)
library(PerformanceAnalytics)
library(PortfolioAnalytics)
library(xts)
library(quantmod)
library(ggplot2)

#solver tools
library(ROI)
library(ROI.plugin.glpk)
library(ROI.plugin.quadprog)
```

#### Importing S&P 500, KOSPI, STI, STOXX600 and 3-Month Treasury Bill Secondary Market Rate

```{r importing data, warning = FALSE, message = FALSE}
#sp500
getSymbols("^SPX", src = "yahoo")
sp500 = SPX["2020/2025-08"]

#KOSPI Composite Index
getSymbols("^KS11", src = "yahoo")
KOSPI = KS11["2020/2025-08"]

#Hang seng Index
getSymbols("^HSI", src = "yahoo")
HSI = HSI["2020/2025-08"]

#Straits Times Index 
getSymbols("^STI", src = "yahoo")
STI = STI["2020/2025-08"]

#STOXX 600
getSymbols("^STOXX", src = "yahoo")
STOXX = STOXX["2020/2025-08"]

#risk-free
getSymbols("WTB3MS", src = "FRED")
rf =  WTB3MS["2020/2025-08"]
```

```{r clean data, warning = FALSE, message = FALSE}
#create a function to subset and aggerate data

get_weekly_retun_data = function(data) {
  weeklydata = to.weekly(data)
  returns = Return.calculate(weeklydata[,6])[-1,]
}

# Calculating returns using adj.close and merge into a data set
sp500_r = get_weekly_retun_data(sp500)
HSI_r = get_weekly_retun_data(HSI)
STI_r = get_weekly_retun_data(STI)
KOSPI_r = get_weekly_retun_data(KOSPI)
sTOXX_r= get_weekly_retun_data(STOXX)

index_returns= merge.xts(sp500_r, HSI_r, KOSPI_r, STI_r, sTOXX_r, fill = na.locf)%>%
  align.time()
names(index_returns) = c("SPX", "HSI", "KOSPI", "STI", "STOXX")
  
#risk-free rate
rf_weekly_close = (1 + rf/100)^(1/52) - 1
rf_weekly_close = rf_weekly_close[-1,]

```


```{r plot returns, warning = FALSE, message = FALSE}
autoplot(index_returns) + labs(x = "weekly", y ="returns (%)", title="Weekly")
```

```{r base specification, warning = FALSE, message = FALSE}
# Portfolio specification object using asset_names
port_spec_base = portfolio.spec(assets = colnames(index_returns))

port_spec_base =   add.objective(portfolio = port_spec_base, type = "return", name = "mean") %>%
  add.objective(type="risk_budget", name="ETL",
# Expected tail loss with a confidence level  0.95;  not asset can contribute more than 60% to total portfolio risk.
                arguments=list(p=0.95), max_prisk=0.60, enabled=FALSE)%>%
  add.constraint(type="leverage",min_sum=0.99, max_sum=1.01) %>%
  add.constraint(type="box", min=0, max=1)
```

```{r mu-sigma, warning = FALSE, message = FALSE}
#risk returns of using sample methods
base_port_1 = port_spec_base  %>% 
  random_portfolios(portfolio=., permutations=5000, rp_method='sample')
base_port_1_mu = applyFUN(index_returns
                          , base_port_1, "mean", list())
base_port_1_sigma = applyFUN(index_returns
                          , base_port_1, "StdDev", list())

chart.Scatter(base_port_1_sigma, base_port_1_mu, main = "mu-sigma of simulation using sample method", col = "#23CE6B")
```
```{r mu-sigma simplex, warning = FALSE, message = FALSE}
base_port_2 = port_spec_base %>%
  random_portfolios(portfolio=., permutations=5000, rp_method='simplex')
base_port_2_mu = applyFUN(index_returns
                          , base_port_2, "mean", list())
base_port_2_sigma = applyFUN(index_returns
                          , base_port_2, "StdDev", list())
chart.Scatter(base_port_2_sigma, base_port_2_mu, main = "mu-sigma of simulation using simplex method", col = "#FF8811")

```
```{r mu-sigma grid, warning = FALSE, message = FALSE}
base_port_3 = port_spec_base %>%
  random_portfolios(portfolio=., permutations=5000, rp_method='grid')%>%
  `colnames<-`(colnames(base_port_1))
base_port_3_mu = applyFUN(index_returns
                          , base_port_3, "mean", list())
base_port_3_sigma = applyFUN(index_returns
                          , base_port_3, "StdDev", list())
chart.Scatter(base_port_3_sigma, base_port_3_mu, main = "mu-sigma of simulation using grid method", col = "purple4")


```
```{r mu-sigma all 3 simulation, warning = FALSE, message = FALSE}
#added "theme" for ggplot graph for consistency
theme = theme(panel.grid.major = element_blank(), #graph element
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          plot.background = element_blank(), 
          axis.line = element_line(colour = "black")) +
        theme(text=element_text(size=15),
             (legend.position="bottom"),
              legend.background = element_blank(),
              legend.box.background = element_rect(colour = "black")) #I split the function into two for readability

#I switched to ggplot fort simplicity 
ggplot() +
  xlab("σ")+
  ylab("μ")+
  labs(title = "mu-sigma",
       subtitle = "all simulated portfolios",
       fill = "Method") +
  geom_point(data = NULL, aes(base_port_3_sigma,base_port_3_mu, fill = "Grid"),  color = "purple4", alpha = 1) +
  geom_point(data = NULL, aes(base_port_1_sigma,base_port_1_mu, fill = "Sample"),  color = "#23CE6B", alpha = .4) +
  geom_point(data = NULL, aes(base_port_2_sigma,base_port_2_mu, fill = "Simplex"),  color = "#FF8811", alpha = .3) +
  theme
```
```{r portfolio specs, warning = FALSE, message = FALSE}
# Portfolio specification
port_spec = portfolio.spec(colnames(index_returns))
port_spec = add.constraint(portfolio = port_spec, type = "full_investment") # weights sum to 1
port_spec = add.constraint(portfolio = port_spec, type = "long_only") # no short
port_spec = add.objective(portfolio = port_spec, type="risk_budget", name="ETL",
                arguments=list(p=0.95), max_prisk=0.60, enabled=FALSE)# Expected tail loss with a confidence level  0.95;  not asset can contribute more than 60% to total portfolio risk.
port_spec = add.objective(portfolio = port_spec, type = "risk", name = "StdDev") # minimize portfolio std
```
```{r portfolio}
# Optimized portfolio
portfolio1 = optimize.portfolio(index_returns, portfolio = port_spec, optimize_method = "ROI", rf=as.numeric(tail(rf_weekly_close,1)) ,  trace = TRUE)
print(portfolio1)

portfolio1_weight = extractWeights(portfolio1) # optimal weights
portfolio1_weight

portfolio1_mu = applyFUN(index_returns
                          , portfolio1_weight, "mean", list())
portfolio1_sigma = applyFUN(index_returns
                          , portfolio1_weight, "StdDev", list())

chart.Weights(portfolio1)


portfolio1_ef = create.EfficientFrontier(index_returns, port_spec, type = "mean-StdDev",
                                         matchcol = "StdDev") 
chart.EF.Weights(portfolio1_ef, n.portfolios = 1000, type="mean-StdDev", 
                 match.col = "StdDev")
chart.EfficientFrontier(portfolio1_ef,
                        n.portfolios = 100,
                        match.col = "StdDev", tangent.line = TRUE, 
                        rf=as.numeric(tail(rf_weekly_close,1)),
                        chart.assets = TRUE, labels.assets = TRUE) 
points(portfolio1_sigma, portfolio1_mu, col = "#800", pch=19)
text(portfolio1_sigma, portfolio1_mu, labels="Optimal Portfolio", cex= .8, pos=2)
```

::: {style="color: red"}
to be continued
:::